name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main-page

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages (main-page folder)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Папка с собранными файлами
          destination_dir: main-page # Папка, куда размещать файлы
