name: Deploy Projects with Build Step

on:
  push:
    branches:
      - main # Запуск при пуше в main ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите свою версию Node.js

      # 3. Собираем и деплоим каждый проект
      - name: Build and deploy changed projects
        run: |
          mkdir -p deploy

          # Список всех папок (проектов) в репозитории
          PROJECTS=$(ls -d */)

          for project in $PROJECTS; do
            if [ -d "$project" ]; then
              echo "Processing $project..."

              # Переходим в директорию проекта
              cd $project

              # Проверяем наличие package.json, если есть - выполняем сборку
              if [ -f "package.json" ]; then
                echo "Running npm install and build for $project..."
                npm install
                npm run build || { echo "Build failed for $project"; exit 1; }
              else
                echo "No package.json in $project. Skipping..."
              fi

              # Копируем собранные файлы в папку для деплоя
              if [ -d "dist" ]; then
                echo "Copying dist folder for $project..."
                cp -r dist ../deploy/$project
              elif [ -d "build" ]; then
                echo "Copying build folder for $project..."
                cp -r build ../deploy/$project
              else
                echo "No dist or build folder found for $project. Skipping..."
              fi

              # Возвращаемся в корневую папку
              cd ..
            fi
          done

      # 4. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
